### ISSUE TITLE
Do we need any new bots?

### ISSUE THREAD

**Issue by Filnor** [SOCVFinder/SOCVFinder.github.io#17]
As far as I know, the coverage of StackOverflow's features by our bots is pretty high, and I can't imagine any new bots that need to be created.

Is my point of view direct?

- If it is, do some bots need rewrites (i.e. for Higgs and/or the SOBotics API) or major changes?
- If it isn't, what new bots do we need? How should they work and interact with the chat and APIs?

**Comment by BasicNullification** [comment]
We could use a bot for catching socks and voting fraud.

**Comment by adeak** [comment]
@K-Davis1 I don't think so. Whatever results such a bot would provide would only be actionable by moderators, meanwhile opening the way to pitchfork-based actions by regular users. Whether true positive or false, regular users should __not__ be provided with potential anomalous voting patterns.

**Comment by ArtOfCode-** [comment]
MOBotics wouldn't object to a voting fraud bot... provided it was actually accurate. Just scrape Magisch's query.

**Comment by adeak** [comment]
I'm fine with working on these things privately, and letting the bots roam in mod bot rooms. My issue is with public bots that readily give users pitchfork material. We all know a handful of users who will flag anything and will likely antagonize/attack whomever they think is in the wrong (even for false positives!).

**Comment by rjrudman** [comment]
@ArtOfCode- Is MOBotics a typo, or is there another channel I'm unaware of?

**Comment by Bhargav-Rao** [comment]
@rjrudman It's another room. Check [this out](https://github.com/SOBotics/UserStalker#join-us-in-mobotics). (And also sorry, won't be able to provide access as it's got some other mod-only data stored)

**Comment by Bhargav-Rao** [comment]
FWIW, I don't see a use for a voting fraud detection bot at the moment (not to disappoint you @K-Davis1, or @paper1111 who's working on one already). The reason is Magisch's SEDE scripts already work quite efficiently, and all the 25 moderators on Stack Overflow can handle them when a flag is raised. As of now the script is fine, and we should probably focus more on other core issues. But if we are building one bot, then yes, I'd agree with @adeak here. It should not be available in a public room. (One other similar bot which I wanted to write was one which detects potentially sensitive data in posts, which I thrashed because of the same fundamental issue)

FWIW, it is better to focus on other aspects of moderation at the moment, and also spend more time improving the current bots. One potential issue which I see is the burgeoning suggested edit queue, which actually caused the moderator election 2017, that issue is still present today, but just a bit smaller. Extending EditMonitor to do that would be a great idea.

**Comment by NobodyNada** [comment]
IMO, a bot to detect voting fraud is a good idea, but it should absolutely not be public.  What about making the results available via a simple web dashboard that requires an invite to access, instead of public chat?

**Comment by Filnor** [comment]
@NobodyNada I prefer the way to "hide" the data behind authorization, but the Bot could still send a message if there are >N open reports (Or simplx maybe add it to Housekeeping/OpenReports).

**Comment by double-fault** [comment]
Would the moderators and community be fine with a private bot (especially one which hunts for fraud and socks)? How would we choose who to give access to?

**Comment by adeak** [comment]
There are two aspects here, I think. One is the source, the other is a running instance. Using a private dashboard would protect the instance, but if the source is public anyone can run their own instance. So I guess something like a private github repo would be necessary to be sure.

**Comment by Filnor** [comment]
@adeak I agree that the source *should* be private, but [UserStalker is also public](https://github.com/SOBotics/UserStalker)...

**Comment by Papershine** [comment]
@Bhargav-rao no problem. TBH I didn't know that Magisch's query existed when I started creating the bot. Also, I'm not sure that the bot could be accurate, since the filters that I had thought up of might not be able to catch anything actually. I'm fine with scrapping the bot anytime, Magisch's query is great enough.


I'm not able to participate in the room meeting next week (primarily because it's 4am for me), so let me point out a bot idea and see how you guys think:

A LQP Monitor: I got this idea from the SOBotics site. The size of the LQP queue is quite high, sometimes even more than the edit queue, so maybe a monitor is needed? (Something like EditMonitor but for the LQP queue)

**Comment by Bhargav-Rao** [comment]
Ah No, don't go to scrape. Try to analyze what it _can_ do and then emulate
the same using API. If you can't do it, then you can call it off as not
accurate.

For the LQPQ Monitor, Petter and Floern have started some work (or rather
lots of work). But as a SO mod, I'd meh. 2 days after election, it'll be
empty. (Because 3 new mods, and they won't know how to handle anything
apart from the NAAs). LQPQ is a bursty queue. Need to do something more
than just a pure monitor. Something like Edit Monitor for the LQPQ would be
good, but not something like SOCVFinder.

**Comment by Bhargav-Rao** [comment]
https://chat.stackoverflow.com/rooms/167761/conversation/2018-03-sobotics-room-meeting-topic-2

- It was decided to create a new repo for holding the new the bot ideas. 
- The bot ideas would then be displayed on the website on a different page
