### ISSUE TITLE
We try to keep SO nice and clean should we do that with our transcript?

### ISSUE THREAD

**Issue by graemeberry** [SOCVFinder/SOCVFinder.github.io#19]
[This](https://github.com/SOBotics/SOBotics.github.io/issues/2) was discussed last year, do we need to revisit this?

Our chatroom is full of posts from all sorts of bots and can get quite cluttered. We see other chatrooms moving messages to another chatroom in an attempt to keep their transcript a little less cluttered. Should we do the same?

I'm thinking things like Natty's output where when the answer has been removed (or let's come up with some criteria) we move the message to another chatroom.

I know it's difficult to do this for every bot we have but I think we should at least discuss it.

**Comment by jdd-software** [comment]
I like this moving deleted post to a "grave yard" would not be bad

I wonder if we could leverage Mayken's userscript somehow (I will ping him just to get an idea).

http://i.stack.imgur.com/KFE8O.png

*if we could have that info in screen shot, it would be easy to remove "Natty, when deleted", "Queen dup when closed", Queen comment, when deleted" etc.*

Removing deleted stuff also will show quicker what is still to be handled 

(I'm not sure what to do with Beli, House and other bot messages, we need to define a strategy for those)

**Comment by makyen** [comment]
What *exact* criteria, on a per message basis (e.g. per bot report type) do you want to consider "complete"?

**Comment by makyen** [comment]
I see two routes. Which you use will depend on what you want/what your actual issue is.

### 1. Don't actually move, use a userscript to hide/make less noticeable completed requests.
* Automatically updated in real-time.
* Leaves the transcript alone, so there's no need to search multiple rooms if you need to find something
  This can be quite beneficial, if someone is going back to investigate something that happened a while ago. From time to time, I've found it frustrating to need to search through 3 different rooms to find out *exactly* what happened in SOCVR.
* Requires that each user install the userscript.
* Does not keep the transcript clean for those without the userscript installed.
  I view this as significantly less of a drawback in a room which is focused on bots vs. SOCVR. In SOCVR there are a number of users which don't/can't use userscripts.


The [beta version of the Unclosed Request Review script](https://chat.stackoverflow.com/transcript/message/41332185#41332185) currently [makes "completed" requests less noticable](https://i.stack.imgur.com/gA36H.gif). It has the user-option to hide completed requests (or not do anything). This script could be modified to expand the definition of what is considered "completed". If you clearly define what you consider "completed", I'm happy to include additional such criteria in the soon-to-be-stock version of the script.

I've always intended this script to be useful for SOBotics, so I have no problem at all enhancing it to provide something that is more beneficial to you.

It's already been asked to include status for comment links. That's in the plan, and some changes heading in that direction have been made (still considerable to go, but much of the base changes should be done for other reasons too).

### 2. Move messages to a different room or rooms.
* This could be a userscript, or an actual bot.
* Keeps the transcript clean for anyone that views it.
* Breaks the transcript into multiple rooms. If someone needs to investigate something that happened some time ago, it's more difficult to do so.
* For every move action, a move-message is created in the transcript of both the source and destination rooms. Thus, this isn't reasonable to do in real-time. Messages should only be moved/archived when there are a "batch" of them to move.
  You can't move the move-messages. I expect that a moderator could delete them, but that seems a bit excessive wrt. cleanup.
* Could be manual or automatic (move when >N messages to archive, or check on some periodic basis and move when > N messages should be archived)

If you're wanting to archive things, then you should probably look at the CVRequestArchiver. It should be easy to modify to support additional rooms (intentionally designed to be so).

The [beta version of the CVRequestArchiver](https://github.com/SO-Close-Vote-Reviewers/UserScripts/blob/Archiver-additions/CVRequestArchiver.user.js) would be reasonably easy to modify to support additional types of messages to move (depending on the criteria you are using, changes should be anywhere from easy/trivial to moderate). What is automatically detected for archiving is driven from a data structure which defines the various criteria for messages to be included. If the available criteria are not sufficient, then it shouldn't be difficult to include additional base criteria. If instructed, it will follow replies, or parents, and include them in the archive task (e.g. for SmokeDetector, it picks up feedback messages like `sd k`).

**Comment by graemeberry** [comment]
Thanks makyen, appreciate the comment on this. I like option 1 and I'm using that US although I haven't gone digging into the settings. Now that you mention it I can see the option to hide which may be the way forward as to accommodate everyone. I think we first need to establish the criteria for each bot and whether or not this is actually a problem to start with but this should give us a good talking point. Thanks again.

**Comment by ArtOfCode-** [comment]
This feels like a discussion that we could/should be leaving for the room meeting to have.

**Comment by Bhargav-Rao** [comment]
https://chat.stackoverflow.com/rooms/167761/conversation/2018-03-sobotics-room-meeting-topic-4

- It was decided that we hide the messages using a Userscript as opposed to moving them. (@makyen's first idea)
