### ISSUE TITLE
Too many pins?

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOCVFinder/SOCVFinder.github.io#6]
We are randomnly pinning a lot of stuff, because we feel it's important. Usually there's 7-8 pins. The page doesn't show most of these. 

So,

1. Do we need to reduce the number of pins?
2. Can we have a better mechanism of announcements?

**Comment by Bhargav-Rao** [comment]
We could have a fixed page, where we make all the latest announcements regarding the bots. That single page can be pinned.

**Comment by Tunaki** [comment]
Definitely too many pins. Only really important announcements should be pinned, and probably mentioned in the site so that it's easily discoverable past the 15 days pin-period.

**Comment by jdd-software** [comment]
Pin pin all thezzz stuff, I like it when people pin if they done something new to a bot, new script etc, but I check everyday, ok if we like to make an announcement page, that works as well

**Comment by Tunaki** [comment]
Or maybe chat messages are getting pinged, because already too much stuff is getting starred (which would be the root issue).

**Comment by Floern** [comment]
1. Pin only important stuff (e.g. [this one](http://chat.stackoverflow.com/transcript/message/35663179#35663179) is not important).
2. Unpin after 48h, because everyone in the room will have seen it by then probably. E.g. what's the point of the "removal of reviewer comments" still being pinned after 4 days?
3. Is there a possibility for a "pin history" where all pinned (and ex-pinned) messages are listed?
4. Also don't star everything, because that forces more messages to be pinned to be visible, as Tunaki said.

**Comment by double-fault** [comment]
I agree with this, though I think making an announcement page is getting two more problems to solve one. IMO, I agree @Floern on this issue. Unpinning after 48h and only pinning important stuff is going to be not at all difficult while it won't even spoil the workflow.

**Comment by Tunaki** [comment]
[Conversation](https://chat.stackoverflow.com/rooms/137476/conversation/2017-03-socvr-room-meeting-topic-6).

Let's have some discussion before pinning something, so that wording and appropriateness can be decided. Only important announcements should be pinned.
